services:
  app:
    container_name: svelte
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "dev"]
    depends_on:
      - sqlite

  sqlite:
    container_name: sqlite3
    build:
      context: ./backend
    ports:
      - "3005:3005"
    volumes:
      - ./db:/db
    tty: true
    command: ["/bin/bash"]
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

